name: Push into master

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./alexamqttbridge
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: chmod +x ./gradlew
    - run: ./gradlew test
      
  build-docker:
    needs: test
    runs-on: ubuntu-latest
    env: 
      LATEST_TAG: ai91/alexamqttbridge:latest
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    defaults:
      run:
        working-directory: ./alexamqttbridge
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: chmod +x ./gradlew
    - run: ./gradlew bootBuildImage --imageName=$LATEST_TAG
    - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - run: docker push $LATEST_TAG
