name: Push into branch

on:
  push:
    branches-ignore: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./alexamqttbridge
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 21
    - run: chmod +x ./gradlew
    - run: ./gradlew test
      
  build-docker:
    needs: test
    runs-on: ubuntu-latest
    env: 
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    defaults:
      run:
        working-directory: ./alexamqttbridge
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 21
    - run: echo "IMAGE_TAG=ai91/alexamqttbridge:${GITHUB_REF##*/}" >> $GITHUB_ENV
    - run: chmod +x ./gradlew
    - run: ./gradlew bootBuildImage --imageName=$IMAGE_TAG
    - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - run: docker push $IMAGE_TAG
